// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class writer_image_sizechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(writer_image_sizechange));
        
        string IMigrationMetadata.Id
        {
            get { return "202106291410330_writer_image_sizechange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
